name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # AdoptOpenJDK (Adoptium) version

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # Checkstyle validation (if needed)
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      # Run the generated Java application (if needed)
      - name: Run application
        run: |
          java -cp build/libs/hexlet.code-1.0-SNAPSHOT.jar hexlet.code.App

      # Run tests with Gradle
      - name: Run tests
        run: ./gradlew test